version: "2"
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_HOST=%
    expose:
    # Opens port 3306 on the container
      - '3306'
    # Where our data will be persisted
    volumes:
      - 'my-db:/var/lib/mysql'
    container_name: mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    hostname: elasticsearch
    ports:
      - "9201:9200"
    container_name: elasticsearch

  redis:
    image: "redis:4.0-alpine"
    command: redis-server
    volumes:
      - "redis:/data"
    container_name: redis
    
  app:
    build: .
    # command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3001:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_NAME=chat_system_development
      - DATABASE_PORT=3306
    volumes:
        - web-app:/chat_system_api
        # - "./config/docker/database.yml:/chat_system_api/config/database.yml"
    container_name: app
    links:
      - db:mysql
    depends_on:
      - db
      - elasticsearch
      - redis

volumes:
  redis:
  db:
  my-db: {}
  web-app: {}