default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  port: 3306
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSEWORD'] %>
development:
  <<: *default

production: 
  <<: *default